"""ticket,ticket status,assigning ticket  models are created

Revision ID: 67051a362a17
Revises: efb1547e92e2
Create Date: 2024-09-20 12:20:09.970421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67051a362a17'
down_revision: Union[str, None] = 'efb1547e92e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_id'), 'ticket', ['id'], unique=False)
    op.create_table('assigning_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('assigned_by_emp_id', sa.String(length=20), nullable=True),
    sa.Column('assigned_to_emp_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_emp_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_emp_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assigning_ticket_id'), 'assigning_ticket', ['id'], unique=False)
    op.create_table('ticket_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('expected_date_to_complete', sa.DateTime(), nullable=True),
    sa.Column('status_of_ticket', sa.Boolean(), nullable=True),
    sa.Column('compiled_date', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_status_id'), 'ticket_status', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_status_id'), table_name='ticket_status')
    op.drop_table('ticket_status')
    op.drop_index(op.f('ix_assigning_ticket_id'), table_name='assigning_ticket')
    op.drop_table('assigning_ticket')
    op.drop_index(op.f('ix_ticket_id'), table_name='ticket')
    op.drop_table('ticket')
    # ### end Alembic commands ###
