"""company name is added in ticket model

Revision ID: 6f43b721f23c
Revises: 67051a362a17
Create Date: 2024-09-20 13:38:38.622588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f43b721f23c'
down_revision: Union[str, None] = '67051a362a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('company_name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'company_name')
    # ### end Alembic commands ###
